### ISSUE TITLE
shell_session lexer: support multiline commands

### ISSUE THREAD

**Issue by tomaskrizek** [jneen/rouge#630]
Line breaks in commands are not recognized and arguments are incorrectly highlighted.

```console
$ gpg2 --output private.key.asc \
       --armor \
       --export-secret-key <keyid>
```

**Comment by jneen** [comment]
This should be fixed in the new `console` lexer: https://github.com/jneen/rouge/blob/master/lib/rouge/lexers/console.rb.

**Comment by jljouannic** [comment]
There is still an issue with multiline commands when there is a comment at the end of one of the lines:

![image](https://user-images.githubusercontent.com/862310/87233538-bbcef700-c3c8-11ea-9f4a-1fdb6d75739e.png)

This is particularly annoying when trying to use [callouts](https://asciidoctor.org/docs/user-manual/#callouts) in an asciidoctor code sample. For example:

```
# sgdisk -n1:0:+512M \ # <1>
    -t1:EF00 \ # <2>
    -c1:esp \ # <3>
    /dev/sda
```

Should I open another issue?

**Comment by jljouannic** [comment]
It is not specific to the presence of a comment at the end of the line. If there is anything after the backslash, the next lines of the command are not correctly coloured.

**Comment by jljouannic** [comment]
I realize that putting a comment after `\` in a multiline command is not supported, and if the sample `sgdisk` command above is copy-paste in a shell session it simply won't work. So adding this kind of support may not be relevant.

In the case of asciidoctor callouts, correct highlighting can still be obtained by removing space between `\` and `#`:
```
# sgdisk -n1:0:+512M \# <1>
    -t1:EF00 \# <2>
    -c1:esp \# <3>
    /dev/sda
```
Giving the following result:
![image](https://user-images.githubusercontent.com/862310/87412478-631a7c80-c5c9-11ea-83ff-8c413c9ce182.png)

**Comment by pyrmont** [comment]
@jljouannic Sorry not to have replied more quickly. Thanks for further investigating this!
